// DO NOT EDIT THIS FILE

[] call compileFinal preprocessFileLineNumbers "deathspawn\Addons\config.sqf";

fn_DS_spawnZone = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\dynamicSpawns.sqf";
fn_DS_zombieAddTabs = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\JohnO_fnc_handleKilled.sqf";
fn_DS_addZombieLoot = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\addZombieLoot.sqf";


JohnO_fnc_zombieBleed = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\JohnO_fnc_zombieBleed.sqf";
JohnO_fnc_fixedZombieSpawn = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\JohnO_fnc_fixedZombieSpawn.sqf";
JohnO_fnc_dynamicZombieSpawn = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\JohnO_fnc_dynamicZombieSpawn.sqf";

Exile_inSafeZone = compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\Exile_inSafeZone.sqf";
JohnO_fnc_zombieInSafeZone =compileFinal preprocessFileLineNumbers "deathspawn\Addons\Scripts\JohnO_fnc_zombieInSafeZone.sqf";

Ryanzombieslogicroam = true; // Dont touch
Ryanzombieshealth = ZMB_HEALTH; // Dont touch
Ryanzombiesdamage = 0.15;  // Dont touch

ZMB_COUNT = 0;

if(ZMB_SIDE == West)then
{
	West setFriend [Resistance, 0];
	Resistance setFriend [West, 0];
};

[] execVM "deathspawn\Addons\spawn_thread.sqf";
[] execVM "deathspawn\Addons\Exile_safeZone_initialize.sqf";

diag_log format["-- DeathSpawn : Initialization Completed -- Zombies will begin spawning in 5 minutes"];

