/**
 * Pre-Initialization
 *
 * DonkeyPuncheD Addon for Exile by DonkeyPunch.INFO
 * www.DonkeyPunch.INFO
 * © 2016 DirtySanchez
 *
 * 
 */
 
private ['_reggedOwners'];
_reggedOwners = [
	"DonkeyPunch Tanoa Exile|APEX Sneak Peek|ALL APEX",
	"[DEV] DonkeyPunch Tanoa Exile|APEX Sneak Peek|ALL APEX",
	"DonkeyPunch Nex Corvus|Brutal Custom Zombie Horde Survival",
	"DonkeyPunch 192.99.150.88 Test Server",
	"DonkeyPunch Exile Conquest Altis",
	"[CDAH] Club der Alten Herren |Exile|PVP|MAS|REVIVE|LOCKPICK|12k",
	"**THOF PVE Exile Chernarus Winter** THOF.Guildlaunch.Com",
	"**THOF PVE Exile Australia** THOF.Guildlaunch.Com",
	"**THOF PVE NAMALSK** THOF.GUILDLAUNCH.COM",
	"/|\|ZOMBIE-Survival|Infection|Militarized\|/|\",
	"{T.S.S|Exile-Zombies,AI,towing and more|Friendly and dedicated admin team|}",
	"{DoD}|Exile by DoOrDieGamers.com|20K Tabs|AI|MISSIONS|MAX LOOT|",
	"[AH]ExileZ|Zombies|NATO_Rus|Extended Base|AI|DMS|ZCP|Apps|Tow|",
	"[AUS] FYC - Napf Highloot|DP-Mod|Ai|Missions|Cup|MAS|PVP",
	"[DarkHavoc] Exile(0.9.6) Zombies | DP | Missions | Towing | more",
	"[DarkHavoc] Exile Test Server (0.9.6|1.56)",
	"[DBD]Exile Altis PVE|CUP|Missions|DP Objects|PVP Zones| 0.9.6",
	"[DBD]Exile Taviana PVE|CUP|Missions|DP Objects|PVP Zones| 0.9.6",
	"[DBD] Clan NAPF Exile PVE|Missions|Roaming AI|Custom Building",
	"[DE-PVE]Die Intelligenz-Allergiker|AI|Viele Missionen|Startgeld",
	"[EU]EnRo#2 Exile ChernarusA3 PVE|Zombies|",
	"[EU-PVE]Nyrp.de Exile 0.9.6|Missions|RoamingAI|AntiPvP|Lottery",
	"[GER]Nyrp - Exile Testing -85.10.203.134",
	"[Ger][RpA]Multigaming Exile AI Base/Missions",
	"[Ger]Enro#4 Exile RPG|enro-griffins.de",
	"[GER]RedWater - Australia - Exile - Military",
	"[GER]Stormtroopers|Missionen|KI|Zombies|AdvBuild",
	"[GER]Stormtroopers|Testserver",
	"[IMA] Exile Lingor PvP |Missions|Towing|Cap |TNA Aint Shit!",
	"[NiW] DEV Exile Esseker v2.0",
	"[NiW] Exile Esseker v2.0",
	"[NL/EU]inTheGame Exile |MAS|dpbuildings|Missions|R AI|Highloot",
	"[NNS]0.9.6POMELO!!ExileCherno24New/ReworkedMissions|FullyMilita",
	"[NNS]|DP|VRGarage|ClaimVehic|AiCity|CutomMap|UGV|UAV|Militarized|",
	"[PCMR] Exile Zombie Madness(0.9.6|1.56)",
	"[RU] Exile *xTeam* PVP|+50K|RHS|JSRS3:DF|Missions|Patrols",
	"[TEST]Exile *xTeam* PVP|RHS|JSRS3:DF|Missions|Patrols",
	"[TR] Exile Türk - [Bank|Level|Missions|NoTrader|WhiteList]",
	"[UK] LG Exile - Cherno - Lottery | Roaming AI | CUP Vehicles |",
	"[UK/EU] ProevoExile [HIGHFPS][MISSIONS][ROAMING_AI]",
	"Adam's Amazing Exile Server",
	"AfterDayOne - Major League Exile Survivalists",
	"Arma 3 exile Vn",
	"BakedBeansKingdom Exile|RHS|NATO|CUPS|TRYK|NAPF",
	"BloodBrothers (Exile 9.41/1.56) PVE ONLY[AI/Mission][TOW]Loot",
	"BMF EXILE TEST SERVER",
	"C][G ExileZ|AI+|MISSIONS|ZOMBIES|CUSTOM|REVIVE|+MORE",
	"DaysAfter Exile Esseker || New Items || Workshop: DaysAfter",
	"DragonsLandRP.co.uk EXILE*ZOMBIES*ESSEKER*CUPS*NATO*",
	"DragonsLandRP.co.uk EXILE*ZOMBIES*Sahrani*CUPS*NATO*",
	"Drone's Custom Exile Server - Altis | PVP| AI | DonkeyPuncheD",
	"Exile Infected",
	"GamersRoost NAPF|AI|CUP|HLC|HVP|TCP|VSM|Virtual Garages",
	"GW Exile/Revive/ExBase/RHS4.1/MASV/MASW/RZInf/ZombDemon",
	"GXA Exile - UnitedSahrani|Custom|CUP|RHS|$8K|ZPC|DP|VR-Garages",
	"GXA Exile-UnitedSahrani|Militarized|+Bases|+Loot|Garages|$8k",
	"GXA Dev",
	"GXA|Exile|Sahrani|Armed|8k|Revive|Heists|DPBase|+Menu|Garages",
	"HEGExile.com|Chernarus|VirtualGarage|Base Raiding|AI Vehicles",
	"HOG Exile | Missions | Tow\Lift\Load\Revive\Rearm\Ebase |",
	"HOG Exile|Missions|50k|Military|Revive|High Loot|Garage|",
	"HGG Exile Zombie Survival",
	"HGG Exile Test Server",
	"HS!-Exile Arma2/3 modded servers",
	"ironEclipse.eu - Ultimate Survival | Esseker",
	"ironEclipse.eu - Ultimate Survival | Namalsk",
	"ironEclipse.eu - Ultimate Survival | Altis",
	"ironEclipse.eu Hard-DayZ Namalsk | Ultimate Survival",
	"KathalonGames.com|Exile Chernarus|PvP|Zombies|AI+Missions|Custo",
	"Keg_Rambo_Exile",
	"Kyle Linden",
	"chez le marcheur // www.chezlemarcheur.com",
	"Serveur test du marcheur",
	"MOONFISH EXILE 0.9.6 ALTIS",
	"MOTO|Esseker|Banking|PvP|Survival|ActiveStaff (0.9.6|1.58)",
	"MOTO|Esseker|Banking|PvP|Survival|ActiveStaff (0.9.6|1.6)",
	"NGC Exile Napf ExtBase RHS",
	"NLG Exile MODS|Custom Map|Random AI| HP: new-life-gaming.de",
	"NTT PVP |DP|HLC|RHS|CUP U/W/V|Lift|Tow|Load|Rev (0.9.6)",
	"OAP test server",
	"ODYSSEY ArmA3 Exile|Under Dev|PVP/DMS|Roaming AI,land,air,vehicle|Host: GTXGaming.co.uk|(0.9.6)",
	"TEST_OFG*EXILE_NAMALSK_ZOMBIES_SURVIVAL_V0.9.6",
	"OFG_EXILE_NAMALSK_ZOMBIES_SURVIVAL_PVP_V0.9.6",
	"Oktoberfest Exile|Zombie@Night|DonkeyPunched|MAS|Revive|AI",
	"Old Guys Gaming Exile PvE Server (0.9.61|1.60)",
	"PhX - Official Test Server",
	"Pirate Hookers Hub (0.9.6)",
	"RPG Exile |Namalsk|Zeds|Missions|Revive|ADVBanking|PVP|",
	"RSGC Exile|Chernarus|10k Start|Militarized|Tanks|XtraBaseParts",
	"RSGC Exile|AlRayak|10k Start|Militarized|Tanks|XtraBaseParts",
	"SniperSchool Exile Custom | work in progress | go live soon",
	"SniperSchool Exile Custom | NEW SERVER |Full Militarized|25K Start|MAS|DPEXILE|TRYK",
	"SoG-Khaos Altis Exile Fully Militarized",
	"SoG-Khaos khaos.redirectme.net Test Server",
	"SOG Post-Apocalyptic Survival | Active Staff | DonkeyPunch |",
	"SSG PVE |DP|HVP|HLC|RHS|CUPV|CUPW|CUPU|Lift|Tow|Load|Rev (0.9.6)",
	"Stay Alive Project | Exile | RHS | Anomalies | Radiation | BlowOut | Crazy AI | Zone-X | AirDrop | HLC | (0.9.6|1.58) |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | ",
	"SWA Exile / PVPE / Revive / Cafting / Extreme Survival",
	"SWA Namalsk Exile / Extreme Suvival / Custom Crafting",
	"SWA DP-Exile / Extreme Survival / Custom Content",
	"TFZ Namalsk Exile|Missions|AI|Tow|Lift|Load|Revive|Rearm|Ebase",
	"The Battlefield [Exile Namalsk|ZCP|StartMoney|RespectLoadout|Mis",
	"The Battlefield | Test Server",
	"The retired Men's Club",
	"The Orders Taviana Militarised|High Loot|CUP|MAS|TRYK|Joint Rail",
	"The Orders Esseker RHS,CUP,HVP,TRYK,Custom Missions",
	"The Orders Chernarus High Loot|CUP|MAS|TRYK|Joint Rail",
	"The Orders Namalsk High Loot|CUP|MAS|RHS|Donkey Punch|TRYK",
	"The Orders Chernarus Winter High Loot|CUP|MAS|RHS|Donkey Punch|",
	"The Orders Napf HighLoot|CUP|MAS|RHS|DonkeyPunch|TRYK|Joint Rail",
	"UKSF Napf - Pre-Alpha - Server Under Construction",
	"X-ALTIS | MODS -> MJQC.ca/EXILE | QC × FR",
	"XxFri3ndlyxX's Exile Server (0.9.6)",
	"=KCK=  EXILE KILLER FPS!!/ZOMBIE/DP/MISSION/20k/REVIVE/MORE",
	"=VGB= VegaZ | The Last Survivors",
	"(GER)-HELL-WOLF-TAVIANA-SERVER- AI Missions and more(0.9.6|1.56)",
	"(GER)-HELL-WOLF-TEST-SERVER- (0.9.6|1.56)"
	
];
if (!(serverName in _reggedOwners)) exitWith 
{
	diag_log format["Your server %1, is not a part of the regged server list. Please contact DirtySanchez with your community information and any donation pages and/or your monetized approved listing. If you are a Pay2Win server you will not be added. If you have had any issues with honoring your agreements with DonkeyPunch Community and/or its affiliates you also will not be added. All DonkeyPunch addons and scripts are the property of DonkeyPunch and without our approval you cannot use/ cannot modify/ cannot redistribute any of our work. This also includes any work provided to the community by the newly formed XLD(eXileLoneDevs) cooperative multi-owner team. If at any point, we deem you unfit to host any of our releases you can be removed without notice.",serverName];
	endMission "Read Your RPT";
};